app:
  timezone: "Asia/Tehran"

gateway:
  host: "0.0.0.0"
  port: "8500"
  whitelist_ip:
    - "x.x.x.x"

bitcoin:
  protocol: "http"
  host: "127.0.0.1"
  port: "8335"
  user: "xxx"
  password: "xxx"

zmq:
  address: "tcp://127.0.0.1:28332"

telegram:
  token: ""
  chat_id: 0